ACHIEVEMENTS_CONFIG = {
    ['win_1'] = { text = "Win 1 game", img = "AwardBadge.webp", index = 1 },
    ['win_10'] = { text = "Win 10 games", img = "AwardRibbon.webp", index = 2},
    ['win_25'] = { text = "Win 25 games", img = "Certificate.webp", index = 3  },
    ['win_50'] = { text = "Win 50 games", img = "ChampionPodium.webp", index = 4 },
    ['win_100'] = { text = "Win 100 games", img = "Crown.webp", index = 5 },
    ['win_200'] = { text = "Win 200 games", img = "Trophy.webp", index = 6 },
    ['reach_podium_10'] = { text = "Reach the podium 10 times", img = "FirstBadgeWinner.webp", index = 7 },
    ['reach_podium_50'] = { text = "Reach the podium 50 times", img = "Flag.webp", index = 8 },
    ['reach_podium_100'] = { text = "Reach the podium 100 times", img = "GraduationCap.webp", index = 9 },
    ['reach_podium_200'] = { text = "Reach the podium 200 times", img = "MovieAward.webp", index = 10 },
    ['complete_50_races'] = { text = "Complete 50 races", img = "MountainFlag.webp", index = 11 },
    ['complete_100_races'] = { text = "Complete 100 races", img = "Shield.webp", index = 12 },
    ['complete_250_races'] = { text = "Complete 250 races", img = "StarBadge.webp", index = 13 },
    ['complete_500_races'] = { text = "Complete 500 races", img = "StarBelt.webp", index = 14 },
    ['win_50_S_race'] = { text = "Win 50 S tier races", img = "StarRibbon.webp", index = 15 },
    ['win_50_A_race'] = { text = "Win 50 A tier races", img = "StarShield.webp", index = 16 },
    ['win_50_B_race'] = { text = "Win 50 B tier races", img = "StarTrophy2.webp", index = 17 },
    ['win_50_C_race'] = { text = "Win 50 C tier races", img = "StarTrophy.webp", index = 18 },
    ['win_50_D_race'] = { text = "Win 50 D tier races", img = "StartFlag.webp", index = 19 },
    ['win_50_ALL_race'] = { text = "Win 50 All tier races", img = "TrophySport.webp", index = 20 },
}