
Config.DevhubSkillTreeEnabled = true -- Enable or disable the skill tree integration

Config.SkillsCategory = {
    skill = 'laptop', 
    title = 'Crime Traders',
}


Config.Skills = {
    ["truckRobbery"] = {
        {
            title = "XP Boost II",
            index = 0,
            description = "Increased XP by 15%",
            lines = { right = false, bottom = false, },
            points = 1,
            icon = "fas fa-star",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_5",
            effect = 15,
        },
        {
            title = "Fast Hack II",
            index = 1,
            description = "Faster hacking of the truck destination by 15%",
            lines = { right = false, left = false, },
            points = 1,
            icon = "fas fa-usb-drive",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_6",
            effect = 15,
        },
        {
            title = "XP Boost III",
            index = 2,
            description = "Increased XP by 10%",
            lines = { left = false, },
            points = 1,
            icon = "fas fa-star",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_7",
            effect = 10,
        },
        {
            title = "Extra Loot II",
            index = 19,
            description = "Chance to receive 1 extra item by 15%",
            lines = { right = false, top = false, },
            points = 1,
            icon = "fas fa-box-open",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_4",
            effect = 15,
        },
        {
            title = "Fast Hack I",
            index = 20,
            description = "Faster hacking of the truck destination by 10%",
            lines = { right = false, left = false, },
            points = 1,
            icon = "fas fa-usb-drive",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_3",
            effect = 10,
        },
        {
            title = "Extra Loot I",
            index = 21,
            description = "Chance to receive 1 extra item by 10%",
            lines = { leftBottom = false, left = false, },
            points = 1,
            icon = "fas fa-box-open",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_2",
            effect = 10,
        },
        {
            text = "Truck Robbery",
            index = 39,
            icon = "fas fa-star",
            lines = { rightTop = false, },
            points = 1,
            unLockable = true,
            description = "Increased XP by 10%",
            title = "XP Boost I",
            img = "https://upload.devhub.gg/dh_upload/truckrobbery.png",
            uid = "truckrobbery_1",
            effect = 10,
        },
    },
    ['airDrops'] = {
                {
            title = "XP Boost II",
            index = 45,
            icon = "fas fa-star",
            lines = { right = false, bottom = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            uid = "airdrops_7",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Quick Unlock II",
            index = 46,
            icon = "fas fa-stopwatch",
            lines = { bottom = false, right = false, left = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            uid = "airdrops_6",
            description = "Faster airdrop opening by 5%",
            effect = 5,
        },
        {
            title = "XP Boost III",
            index = 47,
            icon = "fas fa-star",
            lines = { left = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            uid = "airdrops_5",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Quick Unlock III",
            index = 64,
            icon = "fas fa-stopwatch",
            lines = { top = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            uid = "airdrops_4",
            description = "Faster airdrop opening by 5%",
            effect = 5,
        },
        {
            title = "Item Saver",
            index = 65,
            icon = "fas fa-shield-alt",
            lines = { bottom = false, top = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            description = "",
            uid = "airdrops_3",
        },
        {
            title = "XP Boost I",
            index = 66,
            icon = "fas fa-star",
            lines = { leftBottom = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            uid = "airdrops_2",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Quick Unlock I",
            index = 84,
            icon = "fas fa-stopwatch",
            lines = { top = false, rightTop = false, },
            points = 1,
            text = "Air Drops",
            unLockable = true,
            description = "Faster airdrop opening by 5%",
            uid = "airdrops_1",
            img = "https://upload.devhub.gg/dh_upload/airdrops.png",
            effect = 5,
        },
    },
    ["houseRobbery"] = {
        {
            title = "Tier III",
            index = 110,
            icon = "fas fa-square-3",
            lines = { bottom = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_8",
            description = "Unlocks tier 3 houses",
            effect = 1,
        },
        {
            title = "XP Boost III",
            index = 129,
            icon = "fas fa-star",
            lines = { right = false, top = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_6",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Silent Entry III",
            index = 130,
            description = "Reduced police alert chance by 10%",
            lines = { right = false, left = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_7",
            icon = "fas fa-bell-slash",
            effect = 10,
        },
        {
            title = "XP Boost II",
            index = 131,
            icon = "fas fa-star",
            lines = { left = false, right = false, bottom = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_5",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Tier II",
            index = 132,
            icon = "fas fa-square-2",
            lines = { left = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_9",
            description = "Unlocks tier 2 houses",
            effect = 1,
        },
        {
            title = "Lockpick Mastery",
            index = 148,
            icon = "fas fa-key",
            lines = { right = false, rightBottom = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_2",
            description = "Easier lockpicking chance by 25%",
            effect = 25,
        },
        {
            title = "XP Boost I",
            index = 149,
            icon = "fas fa-star",
            lines = { right = false, left = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_3",
            description = "Increased XP by 10%",
            effect = 10,
        },
        {
            title = "Silent Entry II",
            index = 150,
            icon = "fas fa-bell-slash",
            lines = { left = false, top = false, },
            points = 1,
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_4",
            description = "Reduced police alert chance by 10%",
            effect = 10,
        },
        {
            text = "House Robbery",
            index = 168,
            icon = "fas fa-bell-slash",
            lines = { leftTop = false, },
            points = 1,
            unLockable = true,
            description = "Reduced police alert chance by 5%",
            title = "Silent Entry I",
            img = "https://upload.devhub.gg/dh_upload/houserobbery.png",
            uid = "houserobbery_1",
            effect = 5,
        },
    },
}


    