Config.Lang = {
    -- Error messages
    ['error_no_laptop'] = "No laptop found",
    ['error_app_not_installed'] = "App not installed",
    ['error_invalid_app'] = "Invalid app name",
    ['error_invalid_app_path'] = "Invalid app or path",
    ['error_app_already_installed'] = "App already installed",
    
    -- Notifications
    ['notification_error_opening_app'] = "Error opening app: {error}",
    ['notification_error_closing_app'] = "Error closing app: {error}",
    ['notification_error_minimizing_app'] = "Error minimizing app: {error}",
    ['notification_error_updating_slot'] = "Error updating app slot: {error}",
    ['notification_error_login_status'] = "Error setting login status: {error}",
    ['notification_error_face_id'] = "Error checking Face ID: {error}",
    ['notification_error_face_id_setup'] = "Error setting up Face ID: {error}",
    ['notification_error_installing_app'] = "Error installing app: {error}",
    ['notification_error_uninstalling_app'] = "Error uninstalling app: {error}",
    
    -- CrimeTraders
    ['crimetraders_level_up'] = "Level up! {oldLevel} → {newLevel} for trader {traderId}",
    ['crimetraders_xp_invalid'] = "Invalid XP amount",
    ['crimetraders_trader_invalid'] = "Invalid trader ID",
    ['crimetraders_points_invalid'] = "Invalid points amount",
    ['crimetraders_not_enough_points'] = "Not enough crime points",
    ['crimetraders_item_invalid'] = "Invalid item ID",
    ['crimetraders_price_invalid'] = "Invalid price",
    ['crimetraders_trader_not_found'] = "Trader not found",
    ['crimetraders_level_too_low'] = "Level requirement not met",
    ['crimetraders_item_not_found'] = "Item not found",
    ['crimetraders_on_cooldown'] = "You are on cooldown",
    ['crimetraders_failed_join_queue'] = "Failed to join queue",
    ['crimetraders_failed_leave_queue'] = "Failed to leave queue",
    ['crimetraders_reward_claimed'] = "Reward claimed successfully",
    ['crimetraders_failed_claim_reward'] = "Failed to claim reward",
    ['crimetraders_invalid_parameters'] = "Invalid parameters",
    ['crimetraders_player_not_found'] = "Player not found",
    ['crimetraders_failed_get_user_data'] = "Failed to get user data",
    
    -- UI Notifications
    ['ui_new_update'] = "New update available!",
    ['ui_translation_not_found'] = "Translation for {key} not found",
    
    -- Login Screen
    ['login_incorrect_password'] = "Incorrect password",
    ['login_scanning_face'] = "Scanning Face",
    ['login_face_scan_failed'] = "Face Scan Failed",
    ['login_logging_in'] = "Logging in",
    ['login_user'] = "User",
    ['login_enter_password'] = "Enter password",
    ['login_login'] = "Login",
    
    -- First Boot Setup
    ['setup_loading_devhub'] = "Loading DevhubOS Files",
    ['setup_initializing'] = "Initializing system...",
    ['setup_hardware_check'] = "Checking hardware compatibility...",
    ['setup_system_files'] = "Initializing system files...",
    ['setup_kernel_modules'] = "Loading kernel modules...",
    ['setup_system_components'] = "Configuring system components...",
    ['setup_user_env'] = "Preparing user environment...",
    ['setup_user_interface'] = "Setting up user interface...",
    ['setup_almost_ready'] = "Almost ready...",
    ['setup_devhub_os'] = "DevhubOS",
    ['setup_starting_up'] = "Starting up...",
    ['setup_configure_profile'] = "Configure User Profile",
    ['setup_username'] = "Username",
    ['setup_enter_username'] = "Enter your username",
    ['setup_avatar_selection'] = "Avatar Selection",
    ['setup_wallpaper_selection'] = "Wallpaper Selection",
    ['setup_next'] = "Next",
    ['setup_security_settings'] = "Security Settings",
    ['setup_password_protection'] = "Password Protection",
    ['setup_password_secure'] = "Set password to secure your device",
    ['setup_enter_password'] = "Enter password",
    ['setup_confirm_password'] = "Confirm password",
    ['setup_passwords_mismatch'] = "Passwords do not match",
    ['setup_face_id'] = "Face ID",
    ['setup_face_id_quick'] = "Enable Face ID for quick unlock",
    ['setup_complete_setup'] = "Complete Setup",
    ['setup_complete'] = "Setup Complete!",
    ['setup_welcome'] = "Welcome to DevhubOS, {username}",
    ['setup_almost_done'] = "We are almost done",
    
    -- Settings Screen
    ['settings_wifi'] = "Wifi",
    ['settings_soundless'] = "Soundless",
    ['settings_bluetooth'] = "Bluetooth",
    ['settings_eco_mode'] = "ECO Mode",
    ['settings_change_wallpaper'] = "Change Wallpaper",
    ['settings_security_settings'] = "Security Settings",
    ['settings_new_password'] = "New Password",
    ['settings_enter_new_password'] = "Enter new password",
    ['settings_face_id'] = "Face ID",
    ['settings_enable_face_id'] = "Enable Face ID for quick login",
    ['settings_security_updated'] = "Security settings updated",
    ['settings_edit_account'] = "Edit your account",
    ['settings_username'] = "Username",
    ['settings_enter_username'] = "Enter your username",
    
    -- Taskbar
    ['taskbar_shut_down'] = "Shut Down",
    
    -- Wallpaper
    ['wallpaper_add_new'] = "Add new wallpaper",
    
    -- Calculator
    ['calculator_invalid_expression'] = "Invalid expression",
    
    -- CMD
    ['cmd_welcome'] = "Welcome to DevhubOs CMD v1.0.0\nType 'help' to see available commands.",
    ['cmd_help'] = "Available commands:\n            help - Display this help message\n            clear - Clear the terminal\n            whoami - Display current user\n            date - Display current date and time",
    ['cmd_not_found'] = "%{command}: command not found",
    ['cmd_no_file_dir'] = "%{command}: %{path}: No such file or directory",
    ['cmd_is_directory'] = "%{command}: %{path}: Is a directory",
    ['cmd_missing_file'] = "%{command}: missing file operand",
    ['cmd_permission_denied'] = "Permission denied",
    
    -- Notification
    ['notification_system'] = "System",
    
    -- Notepad
    ['notepad_untitled'] = "Untitled Note",
    ['notepad_new_note'] = "New Note",
    ['notepad_note_title'] = "Note title...",
    ['notepad_write_notes'] = "Write your notes here...",
    ['notepad_save'] = "Save",
    ['notepad_no_note'] = "No note selected",
    ['notepad_create_new'] = "Create a new note",
    ['notepad_loading'] = "Loading...",
    ['notepad_failed_connect'] = "Failed to connect to server",
    ['notepad_note_saved'] = "Note saved successfully",
    ['notepad_failed_save'] = "Failed to save note",
    ['notepad_note_deleted'] = "Note deleted successfully",
    ['notepad_failed_delete'] = "Failed to delete note",
    ['notepad_note_prefix'] = "Note",
    
    -- Clock
    ['clock_sunday'] = "Sunday",
    ['clock_monday'] = "Monday",
    ['clock_tuesday'] = "Tuesday",
    ['clock_wednesday'] = "Wednesday",
    ['clock_thursday'] = "Thursday",
    ['clock_friday'] = "Friday",
    ['clock_saturday'] = "Saturday",
    ['clock_same_time'] = "Same as local time",
    ['clock_hours_ahead'] = "%{hours} hour ahead",
    ['clock_hours_ahead_plural'] = "%{hours} hours ahead",
    ['clock_hours_behind'] = "%{hours} hour behind",
    ['clock_hours_behind_plural'] = "%{hours} hours behind",
    
    -- Browser
    ['browser_enter_url'] = "Enter URL or search...",
    ['browser_loading'] = "Loading...",
    ['browser_title'] = "Web Browser",
    ['browser_search_placeholder'] = "Search or enter URL",
    ['browser_page_error_title'] = "Page Not Available",
    ['browser_page_error_desc'] = "The page you're trying to access cannot be reached. Please check the URL or try again later.",
    ['browser_return_home'] = "Return Home",
    
    -- CrimeTraders UI
    ['crimetraders_ui_tasks'] = "Tasks",
    ['crimetraders_ui_traders'] = "Traders",
    ['crimetraders_ui_no_actions'] = "No crime actions available",
    ['crimetraders_ui_all'] = "All",
    ['crimetraders_ui_purchase_item'] = "Purchase Item",
    ['crimetraders_ui_purchase_confirm'] = "Do you want to purchase {item} for {price} CP?",
    ['crimetraders_ui_balance_new'] = "Your balance new: {balance} CP",
    ['crimetraders_ui_not_enough_cp'] = "You don't have enough CP. You need {needed} more CP.",
    ['crimetraders_ui_purchase'] = "Purchase",
    ['crimetraders_ui_not_enough_cp_button'] = "Not Enough CP",
    ['crimetraders_ui_cancel'] = "Cancel",
    ['crimetraders_ui_purchase_success'] = "Successfully purchased {item}!",
    ['crimetraders_ui_purchase_failed'] = "Failed to purchase item.",
    ['crimetraders_ui_go_back'] = "Go Back",
    ['crimetraders_ui_information'] = "INFORMATION",
    ['crimetraders_ui_rewards'] = "Rewards",
    ['crimetraders_ui_premium_content'] = "PREMIUM CONTENT",
    ['crimetraders_ui_premium_message'] = "Your server does not have access to this exclusive content.",
    ['crimetraders_ui_premium_contact'] = "Contact your server owner to unlock this premium feature.",
    ['crimetraders_ui_xp'] = "Xp",
    ['crimetraders_ui_money'] = "Money",
    ['crimetraders_ui_cp'] = "CP",
    ['crimetraders_ui_tasks_section'] = "Tasks",
    ['crimetraders_ui_no_tasks'] = "No tasks available for this job",
    ['crimetraders_ui_waiting_in_queue'] = "Waiting in queue",
    ['crimetraders_ui_your_position'] = "Your position",
    ['crimetraders_ui_cooldown'] = "Cooldown",
    ['crimetraders_ui_ready'] = "Ready",
    ['crimetraders_ui_reward_available'] = "Reward available",
    ['crimetraders_ui_claiming'] = "Claiming...",
    ['crimetraders_ui_claim_reward'] = "Claim Reward",
    ['crimetraders_ui_joining'] = "Joining...",
    ['crimetraders_ui_join_queue'] = "Join Queue",
    ['crimetraders_ui_on_cooldown'] = "On Cooldown ({cooldown})",
    ['crimetraders_ui_leaving'] = "Leaving...",
    ['crimetraders_ui_leave_queue'] = "Leave Queue",
    ['crimetraders_ui_get_premium'] = "Get Premium Content",
    ['crimetraders_ui_start'] = "Start",
    ['crimetraders_ui_not_owned'] = "Not owned",
    ['crimetraders_ui_premium'] = "Premium",
    ['crimetraders_ui_no_description'] = "No description available",
    ['crimetraders_reward_claimed_title'] = "Reward Claimed",
    ['crimetraders_reward_claimed_message'] = "You have successfully claimed your reward!",
    
    -- App Store
    ['appstore_search'] = "Search...",
    ['appstore_download'] = "Download",
    ['appstore_uninstall'] = "Uninstall",
    ['appstore_no_description'] = "No description available",
    ['appstore_app_not_owned'] = "App not owned",
    ['appstore_premium_title'] = "Premium Experience Awaits",
    ['appstore_premium_exclusive'] = "EXCLUSIVE",
    ['appstore_premium_desc'] = "Unlock premium apps and enhanced gameplay. Contact your server administrator to access this exclusive content.",
    ['appstore_premium_quality'] = "Premium Quality",
    ['appstore_premium_verified'] = "Verified Content",
    ['appstore_premium_button'] = "Get Premium Access",
    ['appstore_app_info'] = "App Information",
    ['appstore_user_reviews'] = "User Reviews",
    ['appstore_go_back'] = "Go Back",
    ['appstore_class'] = "Class",
    ['appstore_premium'] = "Premium",
    ['appstore_regular'] = "Regular",
    ['appstore_rating'] = "Rating",
    ['appstore_author'] = "Author",
    ['appstore_downloads'] = "Downloads",
    ['appstore_above'] = "Above",
    ['appstore_fileSize'] = "File Size",
    ['appstore_mb'] = "MB",
    ['appstore_premiumExperience'] = "Premium Experience Awaits",
    ['appstore_exclusive'] = "Exclusive",
    ['appstore_premiumDescription'] = "Unlock premium apps and enhanced gameplay. Contact your server administrator to access this exclusive content.",
    ['appstore_premiumQuality'] = "Premium Quality",
    ['appstore_verifiedContent'] = "Verified Content",
    ['appstore_getPremiumAccess'] = "Get Premium Access",
    ['appstore_appInformation'] = "App Information",
    ['appstore_seeDetails'] = "See details",
}